name: ar_memory_app
description: تطبيق واقع معزز لحفظ الذكريات في المواقع الجغرافية.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Camera
  camera: ^0.10.5+9
  
  # Location & Maps
  geolocator: ^11.0.0
  google_maps_flutter: ^2.5.3
  permission_handler: ^11.3.0
  
  # Storage
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  
  # UI
  google_fonts: ^6.2.1
  intl: ^0.19.0
  
  # Utilities
  uuid: ^4.3.3

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
