name: Android APK Build

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permissions
        run: |
          chmod +x build_apk.sh
          chmod +x gradlew

      - name: Try Gradle Build First (with fallback)
        id: gradle-build
        continue-on-error: true
        run: ./gradlew assembleDebug --no-daemon
        timeout-minutes: 10

      - name: Build APK using custom script (fallback)
        if: steps.gradle-build.outcome == 'failure'
        run: |
          echo "Gradle build failed, using custom build script..."
          ./build_apk.sh

      - name: Copy APK to root for easy access
        run: |
          if [ -f "app/build/outputs/apk/debug/app-debug.apk" ]; then
            cp app/build/outputs/apk/debug/app-debug.apk ./app-debug.apk
            echo "APK size: $(du -h app-debug.apk | cut -f1)"
            echo "APK built successfully!" >> $GITHUB_STEP_SUMMARY
            echo "- APK Location: \`app-debug.apk\`" >> $GITHUB_STEP_SUMMARY
            echo "- Build Method: ${{ steps.gradle-build.outcome == 'success' && 'Gradle' || 'Custom Script' }}" >> $GITHUB_STEP_SUMMARY
          else
            echo "APK file not found!" >&2
            exit 1
          fi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: |
            app-debug.apk
            app/build/outputs/apk/debug/app-debug.apk
            app/build/outputs/apk/debug/build_report.txt
          retention-days: 30

      - name: Upload Build Logs (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            app/build/outputs/logs/
            *.log
          retention-days: 7
